// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using blazorwasmretainingsearchconditions.Server.Data;

namespace blazorwasmretainingsearchconditions.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210813060153_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("blazorwasmretainingsearchconditions.Shared.Models.Student", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Age = 36,
                            Email = "avril@avril.com",
                            FirstName = "Avril",
                            Gender = "WOMEN",
                            LastName = "Lavigne"
                        },
                        new
                        {
                            Id = 2L,
                            Age = 35,
                            Email = "bruno@bruno.com",
                            FirstName = "Bruno",
                            Gender = "MEN",
                            LastName = "Mars"
                        },
                        new
                        {
                            Id = 3L,
                            Age = 29,
                            Email = "charlie@charlie.com",
                            FirstName = "Charlie",
                            Gender = "MEN",
                            LastName = "Puth"
                        },
                        new
                        {
                            Id = 4L,
                            Age = 30,
                            Email = "ed@ed.com",
                            FirstName = "Ed",
                            Gender = "MEN",
                            LastName = "Sheeran"
                        },
                        new
                        {
                            Id = 5L,
                            Age = 30,
                            Email = "james@james.com",
                            FirstName = "James",
                            Gender = "MEN",
                            LastName = "Bay"
                        },
                        new
                        {
                            Id = 6L,
                            Age = 31,
                            Email = "jess@jess.com",
                            FirstName = "Jess",
                            Gender = "WOMEN",
                            LastName = "Glynne"
                        },
                        new
                        {
                            Id = 7L,
                            Age = 36,
                            Email = "katy@katy.com",
                            FirstName = "Katy",
                            Gender = "WOMEN",
                            LastName = "Perry"
                        },
                        new
                        {
                            Id = 8L,
                            Age = 35,
                            Email = "gaga@gaga.com",
                            FirstName = "Lady",
                            Gender = "WOMEN",
                            LastName = "Gaga"
                        },
                        new
                        {
                            Id = 9L,
                            Age = 50,
                            Email = "michael@michael.com",
                            FirstName = "Michael",
                            Gender = "MEN",
                            LastName = "Jackson"
                        },
                        new
                        {
                            Id = 10L,
                            Age = 29,
                            Email = "sam@sam.com",
                            FirstName = "Sam",
                            Gender = "MEN",
                            LastName = "Smith"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
